-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
    debug = {
        warn = function(message)
            warn(string.format("[fluent debug] warning: %s", message))
        end,

        log = function(message)
            print(string.format("[fluent debug] log: %s", message))
        end,

        error = function(message)
            error(string.format("[fluent debug] error: %s", message))
        end,
    },
}
