name: Release

on:
  workflow_dispatch:
  release:
    types: [published, prereleased]

permissions:
  contents: write
  packages: write

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Checkout
      uses: actions/checkout@v3

    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        version: 9
        run_install: true

    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.3.0

    - name: Install Rojo, Lune and DarkLua
      run: aftman install

    - name: Build and Compile with Rojo
      run: |
        mkdir -p dist
        pnpm run rojo --verbose
        ls dist/

    - name: Build Lua with Lune
      run: |
        lune build
        ls dist/

    - name: Upload Release Assets
      uses: actions/upload-artifact@v3
      with:
        name: release-assets
        path: |
          dist/main.rbxm
          dist/main.lua
